const Telegraf = require('telegraf')
const Scene = require('telegraf/scenes/base')
const Stage = require('telegraf/stage')
const session = require('telegraf/session')
const defaultController = require('./controllers/defaultController')
const mainMenuController = require('./controllers/mainMenuController')
const plantsMenuController = require('./controllers/plantsMenuController')
const timeMenuController = require('./controllers/timeMenuController')
require('dotenv').config()

const mainMenu = new Scene('main-menu')
mainMenu.enter(mainMenuController.enter)
mainMenu.hears(/Мои растения/, mainMenuController.myPlantsCommand)
mainMenu.hears(/Время уведомления/, mainMenuController.timeSettingsCommand)
mainMenu.use(defaultController.errorCommand)

const plantsMenu = new Scene('plants-menu')
plantsMenu.hears(/Добавить растения/, plantsMenuController.addPlantsCommand)
plantsMenu.hears(/Удалить растения/, plantsMenuController.deletePlantsCommand)
plantsMenu.hears(/Изменить время полива/, plantsMenuController.changePlantPeriod)
plantsMenu.hears(/Назад/, defaultController.goToMainMenu)
plantsMenu.use(defaultController.errorCommand)

const timeMenu = new Scene('time-menu')
timeMenu.hears(/[\d]+:\d\d/, timeMenuController.getTimeNotify)
timeMenu.hears(/Назад/, defaultController.goToMainMenu)
timeMenu.use(timeMenuController.wrongTimeFormat)

const stage = new Stage()
stage.register(mainMenu)
stage.register(plantsMenu)
stage.register(timeMenu)

const bot = new Telegraf(process.env.TELEGRAM_TOKEN)
bot.use(session())
bot.use(stage.middleware())
bot.start(defaultController.startReply)
bot.startPolling()

console.log('PlantsBot успешно запущен')